runner:
  golint:
    cmd: golint $(go list ./...)
  govet:
    cmd: go vet $(go list ./...)
  megacheck:
    cmd: megacheck $(go list ./...)
    errorformat:
      - "%f:%l:%c: %m"
  errcheck:
    cmd: errcheck -asserts -ignoretests -blank $(go list ./...)
    errorformat:
      - "%f:%l:%c:%m"