runner:
  golint:
    cmd: golint $(go list ./... | grep -v /vendor/)
  govet:
    cmd: go vet $(go list ./... | grep -v /vendor/)
  # staticcheck, gosimple, unused
  megacheck:
    cmd: megacheck $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  errcheck:
    cmd: errcheck -asserts -ignoretests -blank $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c:%m"