version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Mitu217/tamate
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v -race ./...
