version: 2
jobs:
  build:
    working_directory: /go/src/github.com/go-tamate/tamate
    docker:
      - image: circleci/golang:1.12
        environment:
          - GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          key: gomod-{{ .Branch }}-{{ checksum "go.mod" }}
      - run:
          command: go mod download
      - save_cache:
          key: gomod-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod/cache
      - run: go test -v -race ./...
